export const placeholders = [
  'Lycoris Recoil',
  'Sousou no Frieren',
  'Tensura IV (2/2)',
  'Re:Zero IV (1/2)',
  'Overlord IV',
  '86',
  'Mushoku Tensei III',
  'Fate/Strange Fake (2/2)',
  'Call of The Night',
  'Horimiya: Piece',
  'Witch Hat Atelier',
  'Charlotte',
  'Takt Op. Destiny',
  'Shakugan no Shana',
  'Spice and Wolf',
  'Sonny Boy',
  'Grand Blue',
  'Vivy',
  'Sonny Boy',
  'Nekomonogatari (Kuro)',
  'Owarimonogatari',
  'Hanamonogatari',
  'Kizumonogatari III',
  'Wonder Egg Priority',
  'The Promised Neverland',
  'Urasekai Picnic',
  'Toradora!',
  'The Day I Became a God',
  'Nichijou',
  'Beyond the Boundary',
  'Railgun II',
  'Id: Invaded',
  'Houseki no Kuni',
  'Darling In The FranXX',
  'KonoSuba',
  'Noragami',
  'Kare Kano',
  'Elfen Lied',
  'Sakurasou',
  'Violet Evergarden',
  'NGNL',
  'K-On!',
  'Your Name.'
]