import { Toaster } from "@/components/ui/sonner"
import type { Metadata } from "next"
import { SessionProvider } from "next-auth/react"
import { Geist, Geist_Mono } from "next/font/google"
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full max-w-480 mx-auto flex flex-col font-[Geist]">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}

function Providers({ children }: { children: React.ReactNode }) {
  return (
    <>
      <SessionProvider>
        <NuqsAdapter>
          {children}
        </NuqsAdapter>
      </SessionProvider>

      <Toaster richColors />
    </>
  )
}